/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../../routes/__root'
import { Route as AuthRouteRouteImport } from './../../routes/_auth/route'
import { Route as PublicRouteRouteImport } from './../../routes/_public/route'
import { Route as AuthDashboardRouteImport } from './../../routes/_auth/dashboard'
import { Route as AuthPairRouteImport } from './../../routes/_auth/pair'
import { Route as PublicIndexRouteImport } from './../../routes/_public/index'
import { Route as PublicSignInRouteImport } from './../../routes/_public/sign-in'
import { Route as AuthCSessionIdRouteImport } from './../../routes/_auth/c/$sessionId'
import { Route as ApiAuthSplatRouteImport } from './../../routes/api/auth/$'
import { Route as ApiHostWsRouteImport } from './../../routes/api/host/ws'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthDashboardRoute = AuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthPairRoute = AuthPairRouteImport.update({
  id: '/pair',
  path: '/pair',
  getParentRoute: () => AuthRouteRoute,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicSignInRoute = PublicSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => PublicRouteRoute,
} as any)
const AuthCSessionIdRoute = AuthCSessionIdRouteImport.update({
  id: '/c/$sessionId',
  path: '/c/$sessionId',
  getParentRoute: () => AuthRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHostWsRoute = ApiHostWsRouteImport.update({
  id: '/api/host/ws',
  path: '/api/host/ws',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/dashboard': typeof AuthDashboardRoute
  '/pair': typeof AuthPairRoute
  '/sign-in': typeof PublicSignInRoute
  '/c/$sessionId': typeof AuthCSessionIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/host/ws': typeof ApiHostWsRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/dashboard': typeof AuthDashboardRoute
  '/pair': typeof AuthPairRoute
  '/sign-in': typeof PublicSignInRoute
  '/c/$sessionId': typeof AuthCSessionIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/host/ws': typeof ApiHostWsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_public': typeof PublicRouteRouteWithChildren
  '/_auth/dashboard': typeof AuthDashboardRoute
  '/_auth/pair': typeof AuthPairRoute
  '/_public/sign-in': typeof PublicSignInRoute
  '/_public/': typeof PublicIndexRoute
  '/_auth/c/$sessionId': typeof AuthCSessionIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/host/ws': typeof ApiHostWsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/pair'
    | '/sign-in'
    | '/c/$sessionId'
    | '/api/auth/$'
    | '/api/host/ws'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/pair'
    | '/sign-in'
    | '/c/$sessionId'
    | '/api/auth/$'
    | '/api/host/ws'
  id:
    | '__root__'
    | '/_auth'
    | '/_public'
    | '/_auth/dashboard'
    | '/_auth/pair'
    | '/_public/sign-in'
    | '/_public/'
    | '/_auth/c/$sessionId'
    | '/api/auth/$'
    | '/api/host/ws'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiHostWsRoute: typeof ApiHostWsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/pair': {
      id: '/_auth/pair'
      path: '/pair'
      fullPath: '/pair'
      preLoaderRoute: typeof AuthPairRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/sign-in': {
      id: '/_public/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof PublicSignInRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_auth/c/$sessionId': {
      id: '/_auth/c/$sessionId'
      path: '/c/$sessionId'
      fullPath: '/c/$sessionId'
      preLoaderRoute: typeof AuthCSessionIdRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/host/ws': {
      id: '/api/host/ws'
      path: '/api/host/ws'
      fullPath: '/api/host/ws'
      preLoaderRoute: typeof ApiHostWsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthRouteRouteChildren {
  AuthDashboardRoute: typeof AuthDashboardRoute
  AuthPairRoute: typeof AuthPairRoute
  AuthCSessionIdRoute: typeof AuthCSessionIdRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthDashboardRoute: AuthDashboardRoute,
  AuthPairRoute: AuthPairRoute,
  AuthCSessionIdRoute: AuthCSessionIdRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface PublicRouteRouteChildren {
  PublicSignInRoute: typeof PublicSignInRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicSignInRoute: PublicSignInRoute,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  PublicRouteRoute: PublicRouteRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiHostWsRoute: ApiHostWsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from '../../start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
