/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../../routes/__root'
import { Route as AuthRouteRouteImport } from './../../routes/_auth/route'
import { Route as PublicRouteRouteImport } from './../../routes/_public/route'
import { Route as AuthAppRouteRouteImport } from './../../routes/_auth/_app/route'
import { Route as AuthPairRouteRouteImport } from './../../routes/_auth/pair/route'
import { Route as PublicIndexRouteImport } from './../../routes/_public/index'
import { Route as PublicPrivacyRouteImport } from './../../routes/_public/privacy'
import { Route as PublicSignInRouteImport } from './../../routes/_public/sign-in'
import { Route as PublicTermsRouteImport } from './../../routes/_public/terms'
import { Route as AuthAppRelayRouteRouteImport } from './../../routes/_auth/_app/_relay/route'
import { Route as AuthAppAccountRouteImport } from './../../routes/_auth/_app/account'
import { Route as AuthPairIndexRouteImport } from './../../routes/_auth/pair/index'
import { Route as AuthPairCancelledRouteImport } from './../../routes/_auth/pair/cancelled'
import { Route as AuthPairCodeRouteImport } from './../../routes/_auth/pair/code'
import { Route as AuthPairConfirmRouteImport } from './../../routes/_auth/pair/confirm'
import { Route as AuthPairSuccessRouteImport } from './../../routes/_auth/pair/success'
import { Route as ApiAuthSplatRouteImport } from './../../routes/api/auth/$'
import { Route as ApiCacheImagesRouteImport } from './../../routes/api/cache/images'
import { Route as ApiPairCodeRouteImport } from './../../routes/api/pair/code'
import { Route as AuthAppRelayConversationsIndexRouteImport } from './../../routes/_auth/_app/_relay/conversations/index'
import { Route as AuthAppRelayConversationsConversationIdRouteImport } from './../../routes/_auth/_app/_relay/conversations/$conversationId'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAppRouteRoute = AuthAppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthPairRouteRoute = AuthPairRouteRouteImport.update({
  id: '/pair',
  path: '/pair',
  getParentRoute: () => AuthRouteRoute,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicPrivacyRoute = PublicPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicSignInRoute = PublicSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicTermsRoute = PublicTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => PublicRouteRoute,
} as any)
const AuthAppRelayRouteRoute = AuthAppRelayRouteRouteImport.update({
  id: '/_relay',
  getParentRoute: () => AuthAppRouteRoute,
} as any)
const AuthAppAccountRoute = AuthAppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthAppRouteRoute,
} as any)
const AuthPairIndexRoute = AuthPairIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthPairRouteRoute,
} as any)
const AuthPairCancelledRoute = AuthPairCancelledRouteImport.update({
  id: '/cancelled',
  path: '/cancelled',
  getParentRoute: () => AuthPairRouteRoute,
} as any)
const AuthPairCodeRoute = AuthPairCodeRouteImport.update({
  id: '/code',
  path: '/code',
  getParentRoute: () => AuthPairRouteRoute,
} as any)
const AuthPairConfirmRoute = AuthPairConfirmRouteImport.update({
  id: '/confirm',
  path: '/confirm',
  getParentRoute: () => AuthPairRouteRoute,
} as any)
const AuthPairSuccessRoute = AuthPairSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => AuthPairRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCacheImagesRoute = ApiCacheImagesRouteImport.update({
  id: '/api/cache/images',
  path: '/api/cache/images',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPairCodeRoute = ApiPairCodeRouteImport.update({
  id: '/api/pair/code',
  path: '/api/pair/code',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAppRelayConversationsIndexRoute =
  AuthAppRelayConversationsIndexRouteImport.update({
    id: '/conversations/',
    path: '/conversations/',
    getParentRoute: () => AuthAppRelayRouteRoute,
  } as any)
const AuthAppRelayConversationsConversationIdRoute =
  AuthAppRelayConversationsConversationIdRouteImport.update({
    id: '/conversations/$conversationId',
    path: '/conversations/$conversationId',
    getParentRoute: () => AuthAppRelayRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/pair': typeof AuthPairRouteRouteWithChildren
  '/privacy': typeof PublicPrivacyRoute
  '/sign-in': typeof PublicSignInRoute
  '/terms': typeof PublicTermsRoute
  '/account': typeof AuthAppAccountRoute
  '/pair/cancelled': typeof AuthPairCancelledRoute
  '/pair/code': typeof AuthPairCodeRoute
  '/pair/confirm': typeof AuthPairConfirmRoute
  '/pair/success': typeof AuthPairSuccessRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cache/images': typeof ApiCacheImagesRoute
  '/api/pair/code': typeof ApiPairCodeRoute
  '/pair/': typeof AuthPairIndexRoute
  '/conversations/$conversationId': typeof AuthAppRelayConversationsConversationIdRoute
  '/conversations/': typeof AuthAppRelayConversationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/privacy': typeof PublicPrivacyRoute
  '/sign-in': typeof PublicSignInRoute
  '/terms': typeof PublicTermsRoute
  '/account': typeof AuthAppAccountRoute
  '/pair/cancelled': typeof AuthPairCancelledRoute
  '/pair/code': typeof AuthPairCodeRoute
  '/pair/confirm': typeof AuthPairConfirmRoute
  '/pair/success': typeof AuthPairSuccessRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cache/images': typeof ApiCacheImagesRoute
  '/api/pair/code': typeof ApiPairCodeRoute
  '/pair': typeof AuthPairIndexRoute
  '/conversations/$conversationId': typeof AuthAppRelayConversationsConversationIdRoute
  '/conversations': typeof AuthAppRelayConversationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_public': typeof PublicRouteRouteWithChildren
  '/_auth/_app': typeof AuthAppRouteRouteWithChildren
  '/_auth/pair': typeof AuthPairRouteRouteWithChildren
  '/_public/privacy': typeof PublicPrivacyRoute
  '/_public/sign-in': typeof PublicSignInRoute
  '/_public/terms': typeof PublicTermsRoute
  '/_public/': typeof PublicIndexRoute
  '/_auth/_app/_relay': typeof AuthAppRelayRouteRouteWithChildren
  '/_auth/_app/account': typeof AuthAppAccountRoute
  '/_auth/pair/cancelled': typeof AuthPairCancelledRoute
  '/_auth/pair/code': typeof AuthPairCodeRoute
  '/_auth/pair/confirm': typeof AuthPairConfirmRoute
  '/_auth/pair/success': typeof AuthPairSuccessRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cache/images': typeof ApiCacheImagesRoute
  '/api/pair/code': typeof ApiPairCodeRoute
  '/_auth/pair/': typeof AuthPairIndexRoute
  '/_auth/_app/_relay/conversations/$conversationId': typeof AuthAppRelayConversationsConversationIdRoute
  '/_auth/_app/_relay/conversations/': typeof AuthAppRelayConversationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/pair'
    | '/privacy'
    | '/sign-in'
    | '/terms'
    | '/account'
    | '/pair/cancelled'
    | '/pair/code'
    | '/pair/confirm'
    | '/pair/success'
    | '/api/auth/$'
    | '/api/cache/images'
    | '/api/pair/code'
    | '/pair/'
    | '/conversations/$conversationId'
    | '/conversations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacy'
    | '/sign-in'
    | '/terms'
    | '/account'
    | '/pair/cancelled'
    | '/pair/code'
    | '/pair/confirm'
    | '/pair/success'
    | '/api/auth/$'
    | '/api/cache/images'
    | '/api/pair/code'
    | '/pair'
    | '/conversations/$conversationId'
    | '/conversations'
  id:
    | '__root__'
    | '/_auth'
    | '/_public'
    | '/_auth/_app'
    | '/_auth/pair'
    | '/_public/privacy'
    | '/_public/sign-in'
    | '/_public/terms'
    | '/_public/'
    | '/_auth/_app/_relay'
    | '/_auth/_app/account'
    | '/_auth/pair/cancelled'
    | '/_auth/pair/code'
    | '/_auth/pair/confirm'
    | '/_auth/pair/success'
    | '/api/auth/$'
    | '/api/cache/images'
    | '/api/pair/code'
    | '/_auth/pair/'
    | '/_auth/_app/_relay/conversations/$conversationId'
    | '/_auth/_app/_relay/conversations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCacheImagesRoute: typeof ApiCacheImagesRoute
  ApiPairCodeRoute: typeof ApiPairCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/_app': {
      id: '/_auth/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthAppRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/pair': {
      id: '/_auth/pair'
      path: '/pair'
      fullPath: '/pair'
      preLoaderRoute: typeof AuthPairRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/privacy': {
      id: '/_public/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PublicPrivacyRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/sign-in': {
      id: '/_public/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof PublicSignInRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/terms': {
      id: '/_public/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof PublicTermsRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_auth/_app/_relay': {
      id: '/_auth/_app/_relay'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthAppRelayRouteRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/_app/account': {
      id: '/_auth/_app/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthAppAccountRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/pair/': {
      id: '/_auth/pair/'
      path: '/'
      fullPath: '/pair/'
      preLoaderRoute: typeof AuthPairIndexRouteImport
      parentRoute: typeof AuthPairRouteRoute
    }
    '/_auth/pair/cancelled': {
      id: '/_auth/pair/cancelled'
      path: '/cancelled'
      fullPath: '/pair/cancelled'
      preLoaderRoute: typeof AuthPairCancelledRouteImport
      parentRoute: typeof AuthPairRouteRoute
    }
    '/_auth/pair/code': {
      id: '/_auth/pair/code'
      path: '/code'
      fullPath: '/pair/code'
      preLoaderRoute: typeof AuthPairCodeRouteImport
      parentRoute: typeof AuthPairRouteRoute
    }
    '/_auth/pair/confirm': {
      id: '/_auth/pair/confirm'
      path: '/confirm'
      fullPath: '/pair/confirm'
      preLoaderRoute: typeof AuthPairConfirmRouteImport
      parentRoute: typeof AuthPairRouteRoute
    }
    '/_auth/pair/success': {
      id: '/_auth/pair/success'
      path: '/success'
      fullPath: '/pair/success'
      preLoaderRoute: typeof AuthPairSuccessRouteImport
      parentRoute: typeof AuthPairRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cache/images': {
      id: '/api/cache/images'
      path: '/api/cache/images'
      fullPath: '/api/cache/images'
      preLoaderRoute: typeof ApiCacheImagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pair/code': {
      id: '/api/pair/code'
      path: '/api/pair/code'
      fullPath: '/api/pair/code'
      preLoaderRoute: typeof ApiPairCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/_app/_relay/conversations/': {
      id: '/_auth/_app/_relay/conversations/'
      path: '/conversations'
      fullPath: '/conversations/'
      preLoaderRoute: typeof AuthAppRelayConversationsIndexRouteImport
      parentRoute: typeof AuthAppRelayRouteRoute
    }
    '/_auth/_app/_relay/conversations/$conversationId': {
      id: '/_auth/_app/_relay/conversations/$conversationId'
      path: '/conversations/$conversationId'
      fullPath: '/conversations/$conversationId'
      preLoaderRoute: typeof AuthAppRelayConversationsConversationIdRouteImport
      parentRoute: typeof AuthAppRelayRouteRoute
    }
  }
}

interface AuthAppRelayRouteRouteChildren {
  AuthAppRelayConversationsConversationIdRoute: typeof AuthAppRelayConversationsConversationIdRoute
  AuthAppRelayConversationsIndexRoute: typeof AuthAppRelayConversationsIndexRoute
}

const AuthAppRelayRouteRouteChildren: AuthAppRelayRouteRouteChildren = {
  AuthAppRelayConversationsConversationIdRoute:
    AuthAppRelayConversationsConversationIdRoute,
  AuthAppRelayConversationsIndexRoute: AuthAppRelayConversationsIndexRoute,
}

const AuthAppRelayRouteRouteWithChildren =
  AuthAppRelayRouteRoute._addFileChildren(AuthAppRelayRouteRouteChildren)

interface AuthAppRouteRouteChildren {
  AuthAppRelayRouteRoute: typeof AuthAppRelayRouteRouteWithChildren
  AuthAppAccountRoute: typeof AuthAppAccountRoute
}

const AuthAppRouteRouteChildren: AuthAppRouteRouteChildren = {
  AuthAppRelayRouteRoute: AuthAppRelayRouteRouteWithChildren,
  AuthAppAccountRoute: AuthAppAccountRoute,
}

const AuthAppRouteRouteWithChildren = AuthAppRouteRoute._addFileChildren(
  AuthAppRouteRouteChildren,
)

interface AuthPairRouteRouteChildren {
  AuthPairCancelledRoute: typeof AuthPairCancelledRoute
  AuthPairCodeRoute: typeof AuthPairCodeRoute
  AuthPairConfirmRoute: typeof AuthPairConfirmRoute
  AuthPairSuccessRoute: typeof AuthPairSuccessRoute
  AuthPairIndexRoute: typeof AuthPairIndexRoute
}

const AuthPairRouteRouteChildren: AuthPairRouteRouteChildren = {
  AuthPairCancelledRoute: AuthPairCancelledRoute,
  AuthPairCodeRoute: AuthPairCodeRoute,
  AuthPairConfirmRoute: AuthPairConfirmRoute,
  AuthPairSuccessRoute: AuthPairSuccessRoute,
  AuthPairIndexRoute: AuthPairIndexRoute,
}

const AuthPairRouteRouteWithChildren = AuthPairRouteRoute._addFileChildren(
  AuthPairRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthAppRouteRoute: typeof AuthAppRouteRouteWithChildren
  AuthPairRouteRoute: typeof AuthPairRouteRouteWithChildren
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthAppRouteRoute: AuthAppRouteRouteWithChildren,
  AuthPairRouteRoute: AuthPairRouteRouteWithChildren,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface PublicRouteRouteChildren {
  PublicPrivacyRoute: typeof PublicPrivacyRoute
  PublicSignInRoute: typeof PublicSignInRoute
  PublicTermsRoute: typeof PublicTermsRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicPrivacyRoute: PublicPrivacyRoute,
  PublicSignInRoute: PublicSignInRoute,
  PublicTermsRoute: PublicTermsRoute,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  PublicRouteRoute: PublicRouteRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCacheImagesRoute: ApiCacheImagesRoute,
  ApiPairCodeRoute: ApiPairCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from '../../start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
