/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../../routes/__root'
import { Route as IndexRouteImport } from './../../routes/index'
import { Route as DashboardRouteImport } from './../../routes/dashboard'
import { Route as PairRouteImport } from './../../routes/pair'
import { Route as SignInRouteImport } from './../../routes/sign-in'
import { Route as CSessionIdRouteImport } from './../../routes/c/$sessionId'
import { Route as ApiAuthSplatRouteImport } from './../../routes/api/auth/$'
import { Route as ApiHostWsRouteImport } from './../../routes/api/host/ws'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PairRoute = PairRouteImport.update({
  id: '/pair',
  path: '/pair',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const CSessionIdRoute = CSessionIdRouteImport.update({
  id: '/c/$sessionId',
  path: '/c/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHostWsRoute = ApiHostWsRouteImport.update({
  id: '/api/host/ws',
  path: '/api/host/ws',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/pair': typeof PairRoute
  '/sign-in': typeof SignInRoute
  '/c/$sessionId': typeof CSessionIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/host/ws': typeof ApiHostWsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/pair': typeof PairRoute
  '/sign-in': typeof SignInRoute
  '/c/$sessionId': typeof CSessionIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/host/ws': typeof ApiHostWsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/pair': typeof PairRoute
  '/sign-in': typeof SignInRoute
  '/c/$sessionId': typeof CSessionIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/host/ws': typeof ApiHostWsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/pair'
    | '/sign-in'
    | '/c/$sessionId'
    | '/api/auth/$'
    | '/api/host/ws'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/pair'
    | '/sign-in'
    | '/c/$sessionId'
    | '/api/auth/$'
    | '/api/host/ws'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/pair'
    | '/sign-in'
    | '/c/$sessionId'
    | '/api/auth/$'
    | '/api/host/ws'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  PairRoute: typeof PairRoute
  SignInRoute: typeof SignInRoute
  CSessionIdRoute: typeof CSessionIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiHostWsRoute: typeof ApiHostWsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pair': {
      id: '/pair'
      path: '/pair'
      fullPath: '/pair'
      preLoaderRoute: typeof PairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$sessionId': {
      id: '/c/$sessionId'
      path: '/c/$sessionId'
      fullPath: '/c/$sessionId'
      preLoaderRoute: typeof CSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/host/ws': {
      id: '/api/host/ws'
      path: '/api/host/ws'
      fullPath: '/api/host/ws'
      preLoaderRoute: typeof ApiHostWsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  PairRoute: PairRoute,
  SignInRoute: SignInRoute,
  CSessionIdRoute: CSessionIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiHostWsRoute: ApiHostWsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from '../../start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
